/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class CollectionConfigSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CollectionConfigSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CollectionConfigSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CollectionConfigSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_CollectionConfigSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CollectionConfigSwig() {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_CollectionConfigSwig(), true);
  }

  public void setCapacity(long capacity) {
    IpIntelligenceOnPremiseEngineModuleJNI.CollectionConfigSwig_setCapacity(swigCPtr, this, capacity);
  }

  public void setConcurrency(int concurrency) {
    IpIntelligenceOnPremiseEngineModuleJNI.CollectionConfigSwig_setConcurrency(swigCPtr, this, concurrency);
  }

  public void setLoaded(long loaded) {
    IpIntelligenceOnPremiseEngineModuleJNI.CollectionConfigSwig_setLoaded(swigCPtr, this, loaded);
  }

  public long getCapacity() {
    return IpIntelligenceOnPremiseEngineModuleJNI.CollectionConfigSwig_getCapacity(swigCPtr, this);
  }

  public int getConcurrency() {
    return IpIntelligenceOnPremiseEngineModuleJNI.CollectionConfigSwig_getConcurrency(swigCPtr, this);
  }

  public long getLoaded() {
    return IpIntelligenceOnPremiseEngineModuleJNI.CollectionConfigSwig_getLoaded(swigCPtr, this);
  }

}
