/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class EngineBaseSwig implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EngineBaseSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineBaseSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EngineBaseSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceEngineModuleJNI.delete_EngineBaseSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public void setLicenseKey(String licenceKey) {
    IpIntelligenceEngineModuleJNI.EngineBaseSwig_setLicenseKey(swigCPtr, this, licenceKey);
  }

  public void setDataUpdateUrl(String updateUrl) {
    IpIntelligenceEngineModuleJNI.EngineBaseSwig_setDataUpdateUrl(swigCPtr, this, updateUrl);
  }

  public MetaDataSwig getMetaData() {
    long cPtr = IpIntelligenceEngineModuleJNI.EngineBaseSwig_getMetaData(swigCPtr, this);
    return (cPtr == 0) ? null : new MetaDataSwig(cPtr, false);
  }

  public boolean getAutomaticUpdatesEnabled() {
    return IpIntelligenceEngineModuleJNI.EngineBaseSwig_getAutomaticUpdatesEnabled(swigCPtr, this);
  }

  public ResultsBaseSwig processBase(EvidenceBaseSwig evidence) {
    long cPtr = IpIntelligenceEngineModuleJNI.EngineBaseSwig_processBase(swigCPtr, this, EvidenceBaseSwig.getCPtr(evidence), evidence);
    return (cPtr == 0) ? null : new ResultsBaseSwig(cPtr, true);
  }

  public void refreshData() {
    IpIntelligenceEngineModuleJNI.EngineBaseSwig_refreshData__SWIG_0(swigCPtr, this);
  }

  public void refreshData(String fileName) {
    IpIntelligenceEngineModuleJNI.EngineBaseSwig_refreshData__SWIG_1(swigCPtr, this, fileName);
  }

  public void refreshData(byte[] data) {
    IpIntelligenceEngineModuleJNI.EngineBaseSwig_refreshData__SWIG_2(swigCPtr, this, data);
  }

  public String getDataUpdateUrl() {
    return IpIntelligenceEngineModuleJNI.EngineBaseSwig_getDataUpdateUrl(swigCPtr, this);
  }

  public Date getPublishedTime() {
    return new Date(IpIntelligenceEngineModuleJNI.EngineBaseSwig_getPublishedTime(swigCPtr, this), true);
  }

  public Date getUpdateAvailableTime() {
    return new Date(IpIntelligenceEngineModuleJNI.EngineBaseSwig_getUpdateAvailableTime(swigCPtr, this), true);
  }

  public String getDataFilePath() {
    return IpIntelligenceEngineModuleJNI.EngineBaseSwig_getDataFilePath(swigCPtr, this);
  }

  public String getDataFileTempPath() {
    return IpIntelligenceEngineModuleJNI.EngineBaseSwig_getDataFileTempPath(swigCPtr, this);
  }

  public String getProduct() {
    return IpIntelligenceEngineModuleJNI.EngineBaseSwig_getProduct(swigCPtr, this);
  }

  public String getType() {
    return IpIntelligenceEngineModuleJNI.EngineBaseSwig_getType(swigCPtr, this);
  }

  public VectorStringSwig getKeys() {
    long cPtr = IpIntelligenceEngineModuleJNI.EngineBaseSwig_getKeys(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorStringSwig(cPtr, false);
  }

  public boolean getIsThreadSafe() {
    return IpIntelligenceEngineModuleJNI.EngineBaseSwig_getIsThreadSafe(swigCPtr, this);
  }

}
