/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.hash.engine.onpremise.interop.swig;

public class EvidenceBaseSwig extends MapStringStringSwig implements AutoCloseable {
  private transient long swigCPtr;

  protected EvidenceBaseSwig(long cPtr, boolean cMemoryOwn) {
    super(IpIntelligenceEngineModuleJNI.EvidenceBaseSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EvidenceBaseSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EvidenceBaseSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceEngineModuleJNI.delete_EvidenceBaseSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    this.delete();
  }

  public EvidenceBaseSwig() {
    this(IpIntelligenceEngineModuleJNI.new_EvidenceBaseSwig(), true);
  }

  public void addFromBytes(byte[] key, byte[] value) {
    IPIntelligenceHashEngineModule.Evidence_AddFromBytes(this, key, value);
  }

}
