/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class IpAddressSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IpAddressSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IpAddressSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IpAddressSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_IpAddressSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IpAddressSwig(byte[] ipAddress, IpTypeSwig type) {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_IpAddressSwig__SWIG_0(ipAddress, type.swigValue()), true);
  }

  public IpAddressSwig(String ipAddressString) {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_IpAddressSwig__SWIG_1(ipAddressString), true);
  }

  public void getCopyOfIpAddress(byte[] copy) {
    IpIntelligenceOnPremiseEngineModuleJNI.IpAddressSwig_getCopyOfIpAddress(swigCPtr, this, copy);
  }

  public IpTypeSwig getType() {
    return IpTypeSwig.swigToEnum(IpIntelligenceOnPremiseEngineModuleJNI.IpAddressSwig_getType(swigCPtr, this));
  }

}
