/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.hash.engine.onpremise.interop.swig;

public class IpIntelligenceEngineModule {
  public static void Evidence_AddFromBytes(EvidenceBaseSwig evidence, String key, String value) {
    IpIntelligenceEngineModuleJNI.Evidence_AddFromBytes(EvidenceBaseSwig.getCPtr(evidence), evidence, (key == null) ? null : key.getBytes(), (value == null) ? null : value.getBytes());
  }

  public static StringValueSwig Results_GetValueAsString(ResultsBaseSwig results, String propertyName) {
    return new StringValueSwig(IpIntelligenceEngineModuleJNI.Results_GetValueAsString(ResultsBaseSwig.getCPtr(results), results, (propertyName == null) ? null : propertyName.getBytes()), true);
  }

  public static VectorStringValuesSwig Results_GetValues(ResultsBaseSwig results, String propertyName) {
    return new VectorStringValuesSwig(IpIntelligenceEngineModuleJNI.Results_GetValues(ResultsBaseSwig.getCPtr(results), results, (propertyName == null) ? null : propertyName.getBytes()), true);
  }

  public static BoolValueSwig Results_GetValueAsBool(ResultsBaseSwig results, String propertyName) {
    return new BoolValueSwig(IpIntelligenceEngineModuleJNI.Results_GetValueAsBool(ResultsBaseSwig.getCPtr(results), results, (propertyName == null) ? null : propertyName.getBytes()), true);
  }

  public static IntegerValueSwig Results_GetValueAsInteger(ResultsBaseSwig results, String propertyName) {
    return new IntegerValueSwig(IpIntelligenceEngineModuleJNI.Results_GetValueAsInteger(ResultsBaseSwig.getCPtr(results), results, (propertyName == null) ? null : propertyName.getBytes()), true);
  }

  public static DoubleValueSwig Results_GetValueAsDouble(ResultsBaseSwig results, String propertyName) {
    return new DoubleValueSwig(IpIntelligenceEngineModuleJNI.Results_GetValueAsDouble(ResultsBaseSwig.getCPtr(results), results, (propertyName == null) ? null : propertyName.getBytes()), true);
  }

  public static boolean Results_ContainsProperty(ResultsBaseSwig results, String propertyName) {
    return IpIntelligenceEngineModuleJNI.Results_ContainsProperty(ResultsBaseSwig.getCPtr(results), results, (propertyName == null) ? null : propertyName.getBytes());
  }

}
