/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public final class IpTypeSwig {
  public final static IpTypeSwig FIFTYONE_DEGREES_IP_TYPE_INVALID = new IpTypeSwig("FIFTYONE_DEGREES_IP_TYPE_INVALID", IpIntelligenceOnPremiseEngineModuleJNI.FIFTYONE_DEGREES_IP_TYPE_INVALID_get());
  public final static IpTypeSwig FIFTYONE_DEGREES_IP_TYPE_IPV4 = new IpTypeSwig("FIFTYONE_DEGREES_IP_TYPE_IPV4", IpIntelligenceOnPremiseEngineModuleJNI.FIFTYONE_DEGREES_IP_TYPE_IPV4_get());
  public final static IpTypeSwig FIFTYONE_DEGREES_IP_TYPE_IPV6 = new IpTypeSwig("FIFTYONE_DEGREES_IP_TYPE_IPV6", IpIntelligenceOnPremiseEngineModuleJNI.FIFTYONE_DEGREES_IP_TYPE_IPV6_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IpTypeSwig swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IpTypeSwig.class + " with value " + swigValue);
  }

  private IpTypeSwig(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IpTypeSwig(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IpTypeSwig(String swigName, IpTypeSwig swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IpTypeSwig[] swigValues = { FIFTYONE_DEGREES_IP_TYPE_INVALID, FIFTYONE_DEGREES_IP_TYPE_IPV4, FIFTYONE_DEGREES_IP_TYPE_IPV6 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

