/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class MetaDataSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MetaDataSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MetaDataSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MetaDataSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_MetaDataSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ComponentMetaDataCollectionSwig getComponents() {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getComponents(swigCPtr, this);
    return (cPtr == 0) ? null : new ComponentMetaDataCollectionSwig(cPtr, true);
  }

  public PropertyMetaDataCollectionSwig getProperties() {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getProperties(swigCPtr, this);
    return (cPtr == 0) ? null : new PropertyMetaDataCollectionSwig(cPtr, true);
  }

  public ProfileMetaDataCollectionSwig getProfiles() {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getProfiles(swigCPtr, this);
    return (cPtr == 0) ? null : new ProfileMetaDataCollectionSwig(cPtr, true);
  }

  public ValueMetaDataCollectionSwig getValues() {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getValues(swigCPtr, this);
    return (cPtr == 0) ? null : new ValueMetaDataCollectionSwig(cPtr, true);
  }

  public ValueMetaDataCollectionSwig getValuesForProperty(PropertyMetaDataSwig property) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getValuesForProperty(swigCPtr, this, PropertyMetaDataSwig.getCPtr(property), property);
    return (cPtr == 0) ? null : new ValueMetaDataCollectionSwig(cPtr, true);
  }

  public ValueMetaDataCollectionSwig getValuesForProfile(ProfileMetaDataSwig profile) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getValuesForProfile(swigCPtr, this, ProfileMetaDataSwig.getCPtr(profile), profile);
    return (cPtr == 0) ? null : new ValueMetaDataCollectionSwig(cPtr, true);
  }

  public ComponentMetaDataSwig getComponentForProfile(ProfileMetaDataSwig profile) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getComponentForProfile(swigCPtr, this, ProfileMetaDataSwig.getCPtr(profile), profile);
    return (cPtr == 0) ? null : new ComponentMetaDataSwig(cPtr, true);
  }

  public ComponentMetaDataSwig getComponentForProperty(PropertyMetaDataSwig property) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getComponentForProperty(swigCPtr, this, PropertyMetaDataSwig.getCPtr(property), property);
    return (cPtr == 0) ? null : new ComponentMetaDataSwig(cPtr, true);
  }

  public ProfileMetaDataSwig getDefaultProfileForComponent(ComponentMetaDataSwig component) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getDefaultProfileForComponent(swigCPtr, this, ComponentMetaDataSwig.getCPtr(component), component);
    return (cPtr == 0) ? null : new ProfileMetaDataSwig(cPtr, true);
  }

  public ValueMetaDataSwig getDefaultValueForProperty(PropertyMetaDataSwig property) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getDefaultValueForProperty(swigCPtr, this, PropertyMetaDataSwig.getCPtr(property), property);
    return (cPtr == 0) ? null : new ValueMetaDataSwig(cPtr, true);
  }

  public PropertyMetaDataCollectionSwig getPropertiesForComponent(ComponentMetaDataSwig component) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getPropertiesForComponent(swigCPtr, this, ComponentMetaDataSwig.getCPtr(component), component);
    return (cPtr == 0) ? null : new PropertyMetaDataCollectionSwig(cPtr, true);
  }

  public PropertyMetaDataSwig getPropertyForValue(ValueMetaDataSwig value) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.MetaDataSwig_getPropertyForValue(swigCPtr, this, ValueMetaDataSwig.getCPtr(value), value);
    return (cPtr == 0) ? null : new PropertyMetaDataSwig(cPtr, true);
  }

}
