/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.hash.engine.onpremise.interop.swig;

public class PropertyMetaDataSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PropertyMetaDataSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PropertyMetaDataSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PropertyMetaDataSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceEngineModuleJNI.delete_PropertyMetaDataSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getName() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getName(swigCPtr, this);
  }

  public VectorStringSwig getDataFilesWherePresent() {
    return new VectorStringSwig(IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getDataFilesWherePresent(swigCPtr, this), true);
  }

  public String getType() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getType(swigCPtr, this);
  }

  public String getCategory() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getCategory(swigCPtr, this);
  }

  public String getUrl() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getUrl(swigCPtr, this);
  }

  public boolean getAvailable() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getAvailable(swigCPtr, this);
  }

  public int getDisplayOrder() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getDisplayOrder(swigCPtr, this);
  }

  public boolean getIsMandatory() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getIsMandatory(swigCPtr, this);
  }

  public boolean getIsList() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getIsList(swigCPtr, this);
  }

  public boolean getIsObsolete() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getIsObsolete(swigCPtr, this);
  }

  public boolean getShow() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getShow(swigCPtr, this);
  }

  public boolean getShowValues() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getShowValues(swigCPtr, this);
  }

  public String getDescription() {
    return IpIntelligenceEngineModuleJNI.PropertyMetaDataSwig_getDescription(swigCPtr, this);
  }

}
