/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class RequiredPropertiesConfigSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RequiredPropertiesConfigSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RequiredPropertiesConfigSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RequiredPropertiesConfigSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceEngineModuleJNI.delete_RequiredPropertiesConfigSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RequiredPropertiesConfigSwig() {
    this(IpIntelligenceEngineModuleJNI.new_RequiredPropertiesConfigSwig__SWIG_0(), true);
  }

  public RequiredPropertiesConfigSwig(VectorStringSwig properties) {
    this(IpIntelligenceEngineModuleJNI.new_RequiredPropertiesConfigSwig__SWIG_1(VectorStringSwig.getCPtr(properties), properties), true);
  }

  public RequiredPropertiesConfigSwig(String properties) {
    this(IpIntelligenceEngineModuleJNI.new_RequiredPropertiesConfigSwig__SWIG_2(properties), true);
  }

  public VectorStringSwig getProperties() {
    return new VectorStringSwig(IpIntelligenceEngineModuleJNI.RequiredPropertiesConfigSwig_getProperties(swigCPtr, this), true);
  }

}
