/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class ResultsIpiSwig extends ResultsBaseSwig {
  private transient long swigCPtr;

  protected ResultsIpiSwig(long cPtr, boolean cMemoryOwn) {
    super(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResultsIpiSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ResultsIpiSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_ResultsIpiSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public WeightedStringListValueSwig getValuesAsWeightedStringList(String propertyName) {
    return new WeightedStringListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedStringList__SWIG_0(swigCPtr, this, propertyName), true);
  }

  public WeightedStringListValueSwig getValuesAsWeightedStringList(int requiredPropertyIndex) {
    return new WeightedStringListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedStringList__SWIG_1(swigCPtr, this, requiredPropertyIndex), true);
  }

  public WeightedUTF8StringListValueSwig getValuesAsWeightedUTF8StringList(String propertyName) {
    return new WeightedUTF8StringListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedUTF8StringList__SWIG_0(swigCPtr, this, propertyName), true);
  }

  public WeightedUTF8StringListValueSwig getValuesAsWeightedUTF8StringList(int requiredPropertyIndex) {
    return new WeightedUTF8StringListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedUTF8StringList__SWIG_1(swigCPtr, this, requiredPropertyIndex), true);
  }

  public UTF8StringValueSwig getValueAsUTF8String(String propertyName) {
    return new UTF8StringValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValueAsUTF8String__SWIG_0(swigCPtr, this, propertyName), true);
  }

  public UTF8StringValueSwig getValueAsUTF8String(int requiredPropertyIndex) {
    return new UTF8StringValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValueAsUTF8String__SWIG_1(swigCPtr, this, requiredPropertyIndex), true);
  }

  public WeightedStringListValueSwig getValuesAsWeightedWKTStringList(String propertyName, short decimalPlaces) {
    return new WeightedStringListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedWKTStringList__SWIG_0(swigCPtr, this, propertyName, decimalPlaces), true);
  }

  public WeightedStringListValueSwig getValuesAsWeightedWKTStringList(int requiredPropertyIndex, short decimalPlaces) {
    return new WeightedStringListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedWKTStringList__SWIG_1(swigCPtr, this, requiredPropertyIndex, decimalPlaces), true);
  }

  public WeightedBoolListValueSwig getValuesAsWeightedBoolList(String propertyName) {
    return new WeightedBoolListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedBoolList__SWIG_0(swigCPtr, this, propertyName), true);
  }

  public WeightedBoolListValueSwig getValuesAsWeightedBoolList(int requiredPropertyIndex) {
    return new WeightedBoolListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedBoolList__SWIG_1(swigCPtr, this, requiredPropertyIndex), true);
  }

  public WeightedIntListValueSwig getValuesAsWeightedIntegerList(String propertyName) {
    return new WeightedIntListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedIntegerList__SWIG_0(swigCPtr, this, propertyName), true);
  }

  public WeightedIntListValueSwig getValuesAsWeightedIntegerList(int requiredPropertyIndex) {
    return new WeightedIntListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedIntegerList__SWIG_1(swigCPtr, this, requiredPropertyIndex), true);
  }

  public WeightedDoubleListValueSwig getValuesAsWeightedDoubleList(String propertyName) {
    return new WeightedDoubleListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedDoubleList__SWIG_0(swigCPtr, this, propertyName), true);
  }

  public WeightedDoubleListValueSwig getValuesAsWeightedDoubleList(int requiredPropertyIndex) {
    return new WeightedDoubleListValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValuesAsWeightedDoubleList__SWIG_1(swigCPtr, this, requiredPropertyIndex), true);
  }

  public IpAddressValueSwig getValueAsIpAddress(String propertyName) {
    return new IpAddressValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValueAsIpAddress__SWIG_0(swigCPtr, this, propertyName), true);
  }

  public IpAddressValueSwig getValueAsIpAddress(int requiredPropertyIndex) {
    return new IpAddressValueSwig(IpIntelligenceOnPremiseEngineModuleJNI.ResultsIpiSwig_getValueAsIpAddress__SWIG_1(swigCPtr, this, requiredPropertyIndex), true);
  }

}
