/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class UTF8StringValueSwig implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UTF8StringValueSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UTF8StringValueSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UTF8StringValueSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_UTF8StringValueSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public UTF8StringValueSwig() {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_UTF8StringValueSwig(), true);
  }

  public boolean hasValue() {
    return IpIntelligenceOnPremiseEngineModuleJNI.UTF8StringValueSwig_hasValue(swigCPtr, this);
  }

  public String getNoValueMessage() {
    return IpIntelligenceOnPremiseEngineModuleJNI.UTF8StringValueSwig_getNoValueMessage(swigCPtr, this);
  }

  public UTF8StringSwig getValue() {
    return new UTF8StringSwig(IpIntelligenceOnPremiseEngineModuleJNI.UTF8StringValueSwig_getValue(swigCPtr, this), true);
  }

}
