/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class ValueMetaDataCollectionSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ValueMetaDataCollectionSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ValueMetaDataCollectionSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ValueMetaDataCollectionSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_ValueMetaDataCollectionSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ValueMetaDataSwig getByKey(ValueMetaDataKeySwig key) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.ValueMetaDataCollectionSwig_getByKey(swigCPtr, this, ValueMetaDataKeySwig.getCPtr(key), key);
    return (cPtr == 0) ? null : new ValueMetaDataSwig(cPtr, true);
  }

  public ValueMetaDataSwig getByIndex(long index) {
    long cPtr = IpIntelligenceOnPremiseEngineModuleJNI.ValueMetaDataCollectionSwig_getByIndex(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ValueMetaDataSwig(cPtr, true);
  }

  public long getSize() {
    return IpIntelligenceOnPremiseEngineModuleJNI.ValueMetaDataCollectionSwig_getSize(swigCPtr, this);
  }

}
