/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class VectorStringSwig extends java.util.AbstractList<String> implements AutoCloseable, java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorStringSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorStringSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VectorStringSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_VectorStringSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  @SuppressWarnings("this-escape")
  public VectorStringSwig(String[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (String element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public VectorStringSwig(Iterable<String> initialElements) {
    this();
    for (String element : initialElements) {
      doAdd(element);
    }
  }

  public String get(int index) {
    return doGet(index);
  }

  public String set(int index, String e) {
    return doSet(index, e);
  }

  public boolean add(String e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, String e) {
    modCount++;
    doAdd(index, e);
  }

  public String remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public VectorStringSwig() {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_VectorStringSwig__SWIG_0(), true);
  }

  public VectorStringSwig(VectorStringSwig other) {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_VectorStringSwig__SWIG_1(VectorStringSwig.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_isEmpty(swigCPtr, this);
  }

  public void clear() {
    IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_clear(swigCPtr, this);
  }

  public VectorStringSwig(int count, String value) {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_VectorStringSwig__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_doSize(swigCPtr, this);
  }

  private void doAdd(String x) {
    IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, String x) {
    IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private String doRemove(int index) {
    return IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_doRemove(swigCPtr, this, index);
  }

  private String doGet(int index) {
    return IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_doGet(swigCPtr, this, index);
  }

  private String doSet(int index, String val) {
    return IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    IpIntelligenceOnPremiseEngineModuleJNI.VectorStringSwig_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
