/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class VectorStringValuesSwig implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorStringValuesSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorStringValuesSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VectorStringValuesSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_VectorStringValuesSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public VectorStringValuesSwig() {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_VectorStringValuesSwig(), true);
  }

  public boolean hasValue() {
    return IpIntelligenceOnPremiseEngineModuleJNI.VectorStringValuesSwig_hasValue(swigCPtr, this);
  }

  public String getNoValueMessage() {
    return IpIntelligenceOnPremiseEngineModuleJNI.VectorStringValuesSwig_getNoValueMessage(swigCPtr, this);
  }

  public VectorStringSwig getValue() {
    return new VectorStringSwig(IpIntelligenceOnPremiseEngineModuleJNI.VectorStringValuesSwig_getValue(swigCPtr, this), true);
  }

}
