/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class WeightedUTF8StringListValueSwig implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WeightedUTF8StringListValueSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeightedUTF8StringListValueSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WeightedUTF8StringListValueSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_WeightedUTF8StringListValueSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public WeightedUTF8StringListValueSwig() {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_WeightedUTF8StringListValueSwig(), true);
  }

  public boolean hasValue() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedUTF8StringListValueSwig_hasValue(swigCPtr, this);
  }

  public String getNoValueMessage() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedUTF8StringListValueSwig_getNoValueMessage(swigCPtr, this);
  }

  public WeightedUTF8StringListSwig getValue() {
    return new WeightedUTF8StringListSwig(IpIntelligenceOnPremiseEngineModuleJNI.WeightedUTF8StringListValueSwig_getValue(swigCPtr, this), true);
  }

}
