/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class WeightedDoubleListSwig extends java.util.AbstractList<WeightedValueDoubleSwig> implements AutoCloseable, java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WeightedDoubleListSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeightedDoubleListSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WeightedDoubleListSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_WeightedDoubleListSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public WeightedDoubleListSwig(WeightedValueDoubleSwig[] initialElements) {
    this();
    reserve(initialElements.length);

    for (WeightedValueDoubleSwig element : initialElements) {
      add(element);
    }
  }

  public WeightedDoubleListSwig(Iterable<WeightedValueDoubleSwig> initialElements) {
    this();
    for (WeightedValueDoubleSwig element : initialElements) {
      add(element);
    }
  }

  public WeightedValueDoubleSwig get(int index) {
    return doGet(index);
  }

  public WeightedValueDoubleSwig set(int index, WeightedValueDoubleSwig e) {
    return doSet(index, e);
  }

  public boolean add(WeightedValueDoubleSwig e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, WeightedValueDoubleSwig e) {
    modCount++;
    doAdd(index, e);
  }

  public WeightedValueDoubleSwig remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public WeightedDoubleListSwig() {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_WeightedDoubleListSwig__SWIG_0(), true);
  }

  public WeightedDoubleListSwig(WeightedDoubleListSwig other) {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_WeightedDoubleListSwig__SWIG_1(WeightedDoubleListSwig.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_isEmpty(swigCPtr, this);
  }

  public void clear() {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_clear(swigCPtr, this);
  }

  public WeightedDoubleListSwig(int count, WeightedValueDoubleSwig value) {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_WeightedDoubleListSwig__SWIG_2(count, WeightedValueDoubleSwig.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_doSize(swigCPtr, this);
  }

  private void doAdd(WeightedValueDoubleSwig x) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_doAdd__SWIG_0(swigCPtr, this, WeightedValueDoubleSwig.getCPtr(x), x);
  }

  private void doAdd(int index, WeightedValueDoubleSwig x) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_doAdd__SWIG_1(swigCPtr, this, index, WeightedValueDoubleSwig.getCPtr(x), x);
  }

  private WeightedValueDoubleSwig doRemove(int index) {
    return new WeightedValueDoubleSwig(IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_doRemove(swigCPtr, this, index), true);
  }

  private WeightedValueDoubleSwig doGet(int index) {
    return new WeightedValueDoubleSwig(IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_doGet(swigCPtr, this, index), false);
  }

  private WeightedValueDoubleSwig doSet(int index, WeightedValueDoubleSwig val) {
    return new WeightedValueDoubleSwig(IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_doSet(swigCPtr, this, index, WeightedValueDoubleSwig.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedDoubleListSwig_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
