/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class WeightedValueBoolSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WeightedValueBoolSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeightedValueBoolSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WeightedValueBoolSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceEngineModuleJNI.delete_WeightedValueBoolSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getValue() {
    return IpIntelligenceEngineModuleJNI.WeightedValueBoolSwig_getValue(swigCPtr, this);
  }

  public void setValue(boolean v) {
    IpIntelligenceEngineModuleJNI.WeightedValueBoolSwig_setValue(swigCPtr, this, v);
  }

  public float getWeight() {
    return IpIntelligenceEngineModuleJNI.WeightedValueBoolSwig_getWeight(swigCPtr, this);
  }

  public int getRawWeight() {
    return IpIntelligenceEngineModuleJNI.WeightedValueBoolSwig_getRawWeight(swigCPtr, this);
  }

  public void setRawWeight(int w) {
    IpIntelligenceEngineModuleJNI.WeightedValueBoolSwig_setRawWeight(swigCPtr, this, w);
  }

}
