/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class WeightedIntListSwig extends java.util.AbstractList<WeightedValueIntSwig> implements AutoCloseable, java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WeightedIntListSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeightedIntListSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WeightedIntListSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_WeightedIntListSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public WeightedIntListSwig(WeightedValueIntSwig[] initialElements) {
    this();
    reserve(initialElements.length);

    for (WeightedValueIntSwig element : initialElements) {
      add(element);
    }
  }

  public WeightedIntListSwig(Iterable<WeightedValueIntSwig> initialElements) {
    this();
    for (WeightedValueIntSwig element : initialElements) {
      add(element);
    }
  }

  public WeightedValueIntSwig get(int index) {
    return doGet(index);
  }

  public WeightedValueIntSwig set(int index, WeightedValueIntSwig e) {
    return doSet(index, e);
  }

  public boolean add(WeightedValueIntSwig e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, WeightedValueIntSwig e) {
    modCount++;
    doAdd(index, e);
  }

  public WeightedValueIntSwig remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public WeightedIntListSwig() {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_WeightedIntListSwig__SWIG_0(), true);
  }

  public WeightedIntListSwig(WeightedIntListSwig other) {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_WeightedIntListSwig__SWIG_1(WeightedIntListSwig.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_isEmpty(swigCPtr, this);
  }

  public void clear() {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_clear(swigCPtr, this);
  }

  public WeightedIntListSwig(int count, WeightedValueIntSwig value) {
    this(IpIntelligenceOnPremiseEngineModuleJNI.new_WeightedIntListSwig__SWIG_2(count, WeightedValueIntSwig.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_doSize(swigCPtr, this);
  }

  private void doAdd(WeightedValueIntSwig x) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_doAdd__SWIG_0(swigCPtr, this, WeightedValueIntSwig.getCPtr(x), x);
  }

  private void doAdd(int index, WeightedValueIntSwig x) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_doAdd__SWIG_1(swigCPtr, this, index, WeightedValueIntSwig.getCPtr(x), x);
  }

  private WeightedValueIntSwig doRemove(int index) {
    return new WeightedValueIntSwig(IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_doRemove(swigCPtr, this, index), true);
  }

  private WeightedValueIntSwig doGet(int index) {
    return new WeightedValueIntSwig(IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_doGet(swigCPtr, this, index), false);
  }

  private WeightedValueIntSwig doSet(int index, WeightedValueIntSwig val) {
    return new WeightedValueIntSwig(IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_doSet(swigCPtr, this, index, WeightedValueIntSwig.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedIntListSwig_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
