/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class WeightedUTF8StringListSwig extends java.util.AbstractList<WeightedValueUTF8StringSwig> implements AutoCloseable, java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WeightedUTF8StringListSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeightedUTF8StringListSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WeightedUTF8StringListSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceEngineModuleJNI.delete_WeightedUTF8StringListSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public WeightedUTF8StringListSwig(WeightedValueUTF8StringSwig[] initialElements) {
    this();
    reserve(initialElements.length);

    for (WeightedValueUTF8StringSwig element : initialElements) {
      add(element);
    }
  }

  public WeightedUTF8StringListSwig(Iterable<WeightedValueUTF8StringSwig> initialElements) {
    this();
    for (WeightedValueUTF8StringSwig element : initialElements) {
      add(element);
    }
  }

  public WeightedValueUTF8StringSwig get(int index) {
    return doGet(index);
  }

  public WeightedValueUTF8StringSwig set(int index, WeightedValueUTF8StringSwig e) {
    return doSet(index, e);
  }

  public boolean add(WeightedValueUTF8StringSwig e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, WeightedValueUTF8StringSwig e) {
    modCount++;
    doAdd(index, e);
  }

  public WeightedValueUTF8StringSwig remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public WeightedUTF8StringListSwig() {
    this(IpIntelligenceEngineModuleJNI.new_WeightedUTF8StringListSwig__SWIG_0(), true);
  }

  public WeightedUTF8StringListSwig(WeightedUTF8StringListSwig other) {
    this(IpIntelligenceEngineModuleJNI.new_WeightedUTF8StringListSwig__SWIG_1(WeightedUTF8StringListSwig.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_isEmpty(swigCPtr, this);
  }

  public void clear() {
    IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_clear(swigCPtr, this);
  }

  public WeightedUTF8StringListSwig(int count, WeightedValueUTF8StringSwig value) {
    this(IpIntelligenceEngineModuleJNI.new_WeightedUTF8StringListSwig__SWIG_2(count, WeightedValueUTF8StringSwig.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_doSize(swigCPtr, this);
  }

  private void doAdd(WeightedValueUTF8StringSwig x) {
    IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_doAdd__SWIG_0(swigCPtr, this, WeightedValueUTF8StringSwig.getCPtr(x), x);
  }

  private void doAdd(int index, WeightedValueUTF8StringSwig x) {
    IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_doAdd__SWIG_1(swigCPtr, this, index, WeightedValueUTF8StringSwig.getCPtr(x), x);
  }

  private WeightedValueUTF8StringSwig doRemove(int index) {
    return new WeightedValueUTF8StringSwig(IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_doRemove(swigCPtr, this, index), true);
  }

  private WeightedValueUTF8StringSwig doGet(int index) {
    return new WeightedValueUTF8StringSwig(IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_doGet(swigCPtr, this, index), false);
  }

  private WeightedValueUTF8StringSwig doSet(int index, WeightedValueUTF8StringSwig val) {
    return new WeightedValueUTF8StringSwig(IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_doSet(swigCPtr, this, index, WeightedValueUTF8StringSwig.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    IpIntelligenceEngineModuleJNI.WeightedUTF8StringListSwig_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
