/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.hash.engine.onpremise.interop.swig;

public class WeightedBoolListSwig extends java.util.AbstractList<WeightedValueBoolSwig> implements AutoCloseable, java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WeightedBoolListSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeightedBoolListSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WeightedBoolListSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceEngineModuleJNI.delete_WeightedBoolListSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public WeightedBoolListSwig(WeightedValueBoolSwig[] initialElements) {
    this();
    reserve(initialElements.length);

    for (WeightedValueBoolSwig element : initialElements) {
      add(element);
    }
  }

  public WeightedBoolListSwig(Iterable<WeightedValueBoolSwig> initialElements) {
    this();
    for (WeightedValueBoolSwig element : initialElements) {
      add(element);
    }
  }

  public WeightedValueBoolSwig get(int index) {
    return doGet(index);
  }

  public WeightedValueBoolSwig set(int index, WeightedValueBoolSwig e) {
    return doSet(index, e);
  }

  public boolean add(WeightedValueBoolSwig e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, WeightedValueBoolSwig e) {
    modCount++;
    doAdd(index, e);
  }

  public WeightedValueBoolSwig remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public WeightedBoolListSwig() {
    this(IpIntelligenceEngineModuleJNI.new_WeightedBoolListSwig__SWIG_0(), true);
  }

  public WeightedBoolListSwig(WeightedBoolListSwig other) {
    this(IpIntelligenceEngineModuleJNI.new_WeightedBoolListSwig__SWIG_1(WeightedBoolListSwig.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_isEmpty(swigCPtr, this);
  }

  public void clear() {
    IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_clear(swigCPtr, this);
  }

  public WeightedBoolListSwig(int count, WeightedValueBoolSwig value) {
    this(IpIntelligenceEngineModuleJNI.new_WeightedBoolListSwig__SWIG_2(count, WeightedValueBoolSwig.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_doSize(swigCPtr, this);
  }

  private void doAdd(WeightedValueBoolSwig x) {
    IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_doAdd__SWIG_0(swigCPtr, this, WeightedValueBoolSwig.getCPtr(x), x);
  }

  private void doAdd(int index, WeightedValueBoolSwig x) {
    IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_doAdd__SWIG_1(swigCPtr, this, index, WeightedValueBoolSwig.getCPtr(x), x);
  }

  private WeightedValueBoolSwig doRemove(int index) {
    return new WeightedValueBoolSwig(IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_doRemove(swigCPtr, this, index), true);
  }

  private WeightedValueBoolSwig doGet(int index) {
    return new WeightedValueBoolSwig(IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_doGet(swigCPtr, this, index), false);
  }

  private WeightedValueBoolSwig doSet(int index, WeightedValueBoolSwig val) {
    return new WeightedValueBoolSwig(IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_doSet(swigCPtr, this, index, WeightedValueBoolSwig.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    IpIntelligenceEngineModuleJNI.WeightedBoolListSwig_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
