/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.ipintelligence.engine.onpremise.interop.swig;

public class WeightedValueUTF8StringSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WeightedValueUTF8StringSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeightedValueUTF8StringSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WeightedValueUTF8StringSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IpIntelligenceOnPremiseEngineModuleJNI.delete_WeightedValueUTF8StringSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UTF8StringSwig getValue() {
    return new UTF8StringSwig(IpIntelligenceOnPremiseEngineModuleJNI.WeightedValueUTF8StringSwig_getValue(swigCPtr, this), true);
  }

  public void setValue(UTF8StringSwig v) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedValueUTF8StringSwig_setValue(swigCPtr, this, UTF8StringSwig.getCPtr(v), v);
  }

  public float getWeight() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedValueUTF8StringSwig_getWeight(swigCPtr, this);
  }

  public int getRawWeight() {
    return IpIntelligenceOnPremiseEngineModuleJNI.WeightedValueUTF8StringSwig_getRawWeight(swigCPtr, this);
  }

  public void setRawWeight(int w) {
    IpIntelligenceOnPremiseEngineModuleJNI.WeightedValueUTF8StringSwig_setRawWeight(swigCPtr, this, w);
  }

}
